spring:
    application:
        name: fable-minds
    profiles:
        active: test
    output:
        ansi:
            enabled: ALWAYS
jwt:
    secret: 0123456789abcdef0123456789abcdef
    expiration: 86400000