spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/fabledb
        username: root
        password: pass
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        show-sql: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect