spring:
    datasource:
        url: jdbc:postgresql://ep-snowy-boat-a4p9m5i9-pooler.us-east-1.aws.neon.tech/fabledb?sslmode=require
        username: root
        password: npg_F7Mpf2bdQyji
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    ai:
        openai:
            api-key: ${SPRING_AI_OPENAI_API_KEY}
            base-url: https://api.groq.com/openai
            chat:
                options:
                    model: mixtral-8x7b-32768
            client:
                connect-timeout: 10s
                read-timeout: 30s
    autoconfigure:
        exclude:
        - org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
logging:
    level:
        "[org.springframework.ai]": TRACE
        "[org.springframework]": DEBUG
        hibernate:
            SQL: DEBUG
            type:
            descriptor:
                sql:
                BasicBinder: TRACE